//! Hostile entity implementations.
//!
//! Those mobs are aggressive creatures that attack players on sight.

mod blaze;
mod bogged;
mod breeze;
mod copper_golem;
mod creaking;
pub mod creeper;
mod drowned;
mod elder_guardian;
pub mod endermite;
mod evoker;
mod ghast;
mod giant;
mod guardian;
mod hoglin;
mod husk;
mod illusioner;
mod magma_cube;
mod parched;
mod phantom;
mod piglin_brute;
mod pillager;
mod ravager;
mod shulker;
mod silverfish;
pub mod skeleton;
mod slime;
mod snow_golem;
mod stray;
mod sulfur_cube;
mod vex;
mod vindicator;
mod warden;
mod witch;
mod wither_skeleton;
pub mod zombie;
mod zoglin;
mod zombie_villager;

#[cfg(test)]
mod tests;

pub use blaze::BlazeEntity;
pub use bogged::BoggedEntity;
pub use breeze::BreezeEntity;
pub use copper_golem::CopperGolemEntity;
pub use creaking::CreakingEntity;
pub use creeper::CreeperEntity;
pub use drowned::DrownedEntity;
pub use elder_guardian::ElderGuardianEntity;
pub use endermite::EndermiteEntity;
pub use evoker::EvokerEntity;
pub use ghast::{GhastEntity, HappyGhastEntity};
pub use giant::GiantEntity;
pub use guardian::GuardianEntity;
pub use hoglin::HoglinEntity;
pub use husk::HuskEntity;
pub use illusioner::IllusionerEntity;
pub use magma_cube::MagmaCubeEntity;
pub use parched::ParchedEntity;
pub use phantom::PhantomEntity;
pub use piglin_brute::PiglinBruteEntity;
pub use pillager::PillagerEntity;
pub use ravager::RavagerEntity;
pub use shulker::ShulkerEntity;
pub use silverfish::SilverfishEntity;
pub use skeleton::SkeletonEntity;
pub use slime::SlimeEntity;
pub use snow_golem::SnowGolemEntity;
pub use stray::StrayEntity;
pub use sulfur_cube::SulfurCubeEntity;
pub use vex::VexEntity;
pub use vindicator::VindicatorEntity;
pub use warden::WardenEntity;
pub use witch::WitchEntity;
pub use wither_skeleton::WitherSkeletonEntity;
pub use zoglin::ZoglinEntity;
pub use zombie::ZombieEntity;
pub use zombie_villager::ZombieVillagerEntity;
