//! Passive entity implementations.
/// Those mobs are passive creatures that run away when attacked by a player.
mod allay;
mod armadillo;
mod axolotl;
mod bat;
mod cat;
mod chicken;
mod cod;
mod cow;
mod dolphin;
mod donkey;
mod fox;
mod frog;
mod glow_squid;
mod horse;
mod llama;
mod mooshroom;
mod mule;
mod nautilus;
mod ocelot;
mod panda;
mod parrot;
mod pig;
mod pufferfish;
mod rabbit;
mod salmon;
mod sheep;
mod skeleton_horse;
mod sniffer;
mod squid;
mod strider;
mod tadpole;
mod tropical_fish;
mod turtle;
mod villager;
mod wandering_trader;
mod zombie_horse;

pub use allay::AllayEntity;
pub use armadillo::ArmadilloEntity;
pub use axolotl::AxolotlEntity;
pub use bat::BatEntity;
pub use cat::CatEntity;
pub use chicken::ChickenEntity;
pub use cod::CodEntity;
pub use cow::CowEntity;
pub use dolphin::DolphinEntity;
pub use donkey::DonkeyEntity;
pub use fox::FoxEntity;
pub use frog::FrogEntity;
pub use glow_squid::GlowSquidEntity;
pub use horse::HorseEntity;
pub use llama::{LlamaEntity, TraderLlamaEntity};
pub use mooshroom::MushroomCowEntity;
pub use mule::MuleEntity;
pub use nautilus::{NautilusEntity, ZombieNautilusEntity};
pub use ocelot::OcelotEntity;
pub use panda::PandaEntity;
pub use parrot::ParrotEntity;
pub use pig::PigEntity;
pub use pufferfish::PufferfishEntity;
pub use rabbit::RabbitEntity;
pub use salmon::SalmonEntity;
pub use sheep::SheepEntity;
pub use skeleton_horse::SkeletonHorseEntity;
pub use sniffer::SnifferEntity;
pub use squid::SquidEntity;
pub use strider::StriderEntity;
pub use tadpole::TadpoleEntity;
pub use tropical_fish::TropicalFishEntity;
pub use turtle::TurtleEntity;
pub use villager::VillagerEntity;
pub use wandering_trader::WanderingTraderEntity;
pub use zombie_horse::ZombieHorseEntity;
